Feature/enforced binary guild implementation
DXgovernance/dxdao-contracts pull request #102
Opened 2022-03-31 14:26 UTC by mprasanjith

2022-04-01 09:43 UTC, rossneilson commented on contracts/erc20guild/implementations/EnforcedBinaryGuild.sol
> +    // @param totalActions The amount of actions that would be offered to the voters
I would maybe include that the total actions is excluding the against vote in this comment

2022-04-01 10:20 UTC, rossneilson commented on contracts/erc20guild/implementations/EnforcedBinaryGuild.sol
> +        return _createProposal(_to, _data, _value, totalActions, title, contentHash);
Chatted with madusha about this and likely we should call the inherited method in the same way on both methods

2022-04-03 23:37 UTC, AugustoL requested changes

2022-04-03 23:37 UTC, AugustoL commented on contracts/erc20guild/implementations/EnforcedBinaryGuild.sol
> +        totalActions += 1;
use safeMath here please

2022-04-04 05:38 UTC, mprasanjith commented on contracts/erc20guild/implementations/EnforcedBinaryGuild.sol
> +        totalActions += 1;
Rookie mistake! Fixed.

2022-04-06 14:44 UTC, merged