Allow anyone to call shareSignedVote
DXgovernance/dxdao-contracts pull request #103
Opened 2022-03-31 17:43 UTC by hhamud

* Closes #98

2022-04-03 23:28 UTC, AugustoL requested changes
Dont use try and catch in the tests, use expectRevert and also check the vote amount on the proposal chaged or not (depending in the test case) after the ShareSignedVote tx

2022-04-03 23:28 UTC, AugustoL commented on contracts/dxvote/DXDVotingMachine.sol
> +        address voter,
Lets put voter after proposalId and before vote decision, like the order of the VoteSIgned event parameters

2022-04-04 12:08 UTC, hhamud commented on contracts/dxvote/DXDVotingMachine.sol
> +        address voter,
Good point, I'll rewrite that test

2022-04-04 23:37 UTC, AugustoL approved these changes

2022-04-05 12:38 UTC, merged