Feature/votingmachine withdraw refund balance
DXgovernance/dxdao-contracts pull request #110
Opened 2022-04-05 01:03 UTC by MiltonTulli

## Summary
- Add DXDVotingMachine function to withdraw refund balance
- Add tests
- Fix DXDVotingMachine tests failing because PermissionRegistry.setAdminPermission method was renamed but test wasn't updated.

<img width="738" alt="Screen Shot 2022-04-04 at 22 02 18" src="https://user-images.githubusercontent.com/25844967/161657760-d96ecc6b-8f80-4ff9-b50d-0e4f6c551d2a.png">

2022-04-05 12:16 UTC, AugustoL requested changes

2022-04-05 12:16 UTC, AugustoL commented on contracts/dxvote/DXDVotingMachine.sol
> +            organizationRefunds[msg.sender].voteGas > 0 || organizationRefunds[msg.sender].maxGasPrice > 0,
Lets check only voteGas > 0

2022-04-05 12:16 UTC, AugustoL commented on contracts/dxvote/DXDVotingMachine.sol
> +        msg.sender.transfer(amount);
msg.sender.transfer(organizationRefunds[msg.sender].balance);

2022-04-05 14:12 UTC, MiltonTulli commented on contracts/dxvote/DXDVotingMachine.sol
> +        msg.sender.transfer(amount);
Sure, done. Can I ask why? Is it to save space by avoiding the `amount` declaration?

2022-04-06 14:22 UTC, AugustoL approved these changes

2022-04-06 14:27 UTC, merged