feat: Adding member count logic to snapshot implementation
DXgovernance/dxdao-contracts pull request #128
Opened 2022-04-20 16:41 UTC by rossneilson

Adding to snapshot lock and withdraw token implementation as currently it always stays at 1

2022-04-20 21:34 UTC, AugustoL requested changes

2022-04-20 21:34 UTC, AugustoL commented on contracts/erc20guild/implementations/SnapshotERC20Guild.sol
> +        if (tokensLocked[msg.sender].amount == 0) totalMembers = totalMembers.add(1);
add linebreak for if/else

2022-04-20 21:35 UTC, AugustoL commented on contracts/erc20guild/implementations/SnapshotERC20Guild.sol
> +        if (tokensLocked[msg.sender].amount == 0) totalMembers = totalMembers.add(1);
Also, do we have tests for this contract? if so add the check in the tests

2022-04-20 22:11 UTC, rossneilson commented on contracts/erc20guild/implementations/SnapshotERC20Guild.sol
> +        if (tokensLocked[msg.sender].amount == 0) totalMembers = totalMembers.add(1);
The erc20 guild implementation that you did doesnt have line breaks, should I add there too? Its not auto adding them.
And will add a test or two

2022-04-20 23:16 UTC, AugustoL commented on contracts/erc20guild/implementations/SnapshotERC20Guild.sol
> +        if (tokensLocked[msg.sender].amount == 0) totalMembers = totalMembers.add(1);
hmmm, I though we were requesting line breaks, I always use them. ok leave it then

2022-04-23 14:45 UTC, AugustoL approved these changes

2022-04-25 09:24 UTC, merged