Feature/add total member
DXgovernance/dxdao-contracts pull request #131
Opened 2022-04-25 07:56 UTC by Kenny-Gin1

Issue: https://github.com/DXgovernance/dxdao-contracts/issues/129

- Added a `totalHolder` count for our `ERC20SnapshotRep.sol` contract
- Added a mock for testing `internal` functions and simplifying `mint` functions
- Added tests

Was trying to figure out how to test internal functions and simplify minting. The best practice seemed to just make an inheritance contract overriding functions and exposing internal functions. Let me know if this is the way we should do it, and if there are eventual other issues with this approach.

2022-04-25 09:25 UTC, rossneilson commented on contracts/utils/ERC20/ERC20SnapshotRep.sol
> +import "@openzeppelin/contracts-upgradeable/utils/math/SafeMathUpgradeable.sol";
We shouldnt need safemath for 0.8 right?

2022-04-25 12:40 UTC, AugustoL commented on contracts/utils/ERC20/ERC20SnapshotRep.sol
> +import "@openzeppelin/contracts-upgradeable/utils/math/SafeMathUpgradeable.sol";
I think we dont, but we are still using the openzeppelin libs.

2022-04-25 12:40 UTC, AugustoL commented on contracts/test/ERC20SnapshotRepMock.sol
> +    function mint(address to, uint256 amount) public override {
This funcion is not needed, the mint are burned are defined in the ERC20SnapshotRep for only owner

2022-04-25 12:42 UTC, AugustoL commented on contracts/test/ERC20SnapshotRepMock.sol
> +    function _beforeTokenTransfer(
looks like thsi fixes a wront use of _beforeTokenTransfer in ERC20SnapshotRep, where the _beforeTokenTransfer uses onlyOwner.

Just remove the 
```
    function _beforeTokenTransfer(
        address from,
        address to,
        uint256 amount
    ) internal virtual override onlyOwner {}
    ``` in the ERC20SnapshotRep and you should be able to remove this _beforeTokenTransfer and everything should work.

2022-04-25 17:55 UTC, Kenny-Gin1 commented
@rossneilson @AugustoL Thanks for your feedback I've now fixed it in regards to that.

- Changed from plural to singular regarding `addHolder` and `removeHolder` functions
- Removed the `mint` and `_beforeTokenTransfer` functions
- Changed the tests to better reflect usage
- Removed `SafeMath` library since Solidity checks for overflows by default in version 0.8 <

2022-04-25 19:52 UTC, AugustoL commented
Also, does all tests run succesfully? the test actions failed https://github.com/DXgovernance/dxdao-contracts/runs/6162734754?check_suite_focus=true

2022-04-26 06:46 UTC, Kenny-Gin1 commented
> Also, does all tests run succesfully? the test actions failed https://github.com/DXgovernance/dxdao-contracts/runs/6162734754?check_suite_focus=true

Yes! I will look at it together today with @MiltonTulli before merging. Because I think it's in regards to calling the `mint` in `ERC20SnapshotRep`which has the `_snapshot()` function in it.

2022-04-26 11:46 UTC, AugustoL approved these changes

2022-04-26 11:49 UTC, AugustoL commented
one tests in failing in the CI

2022-04-26 12:11 UTC, AugustoL requested changes
@Kenny-Gin1 try merging with develop, fix tests and commit

2022-04-27 08:26 UTC, Kenny-Gin1 commented
@AugustoL @MiltonTulli realised that removing this part:     

```
function _beforeTokenTransfer(
        address from,
        address to,
        uint256 amount
    ) internal virtual override onlyOwner {}
```

from the `ERC20SnapshotRep` made one of @MiltonTulli tests fail. Should it still be removed? Are we testing it wrongly for some reason?

2022-04-27 13:24 UTC, Kenny-Gin1 commented
Alright, all tests are working ✅  @rossneilson @AugustoL

2022-04-27 13:52 UTC, AugustoL requested changes

2022-04-27 13:52 UTC, AugustoL commented on package.json
> -      "git add",
remove git add too please.

After commit if you have changes left you can add them with `git add -p` and `git commit --amend`

2022-04-27 14:39 UTC, AugustoL approved these changes

2022-04-27 16:13 UTC, MiltonTulli approved these changes

2022-04-27 16:13 UTC, MiltonTulli commented on test/utils/ERC20/ERC20SnapshotRep.js
> +    await ERC20SnapshotRep._addHolder(SOME_ADDRESS, { from: accounts[0] });
@Kenny-Gin1 I think that you can omit `, {from : accounts[0]}` in all contract function executions. By default will execute with the owner (L.14). 

```
await ERC20SnapshotRep._addHolder(SOME_ADDRESS);
await ERC20SnapshotRep._removeHolder(SOME_ADDRESS);
await ERC20SnapshotRep.mint(SOME_ADDRESS, 100);
await ERC20SnapshotRep.burn(SOME_ADDRESS, 50);
```

2022-04-27 16:38 UTC, merged