Feature/deploy guilds script
DXgovernance/dxdao-contracts pull request #137
Opened 2022-04-27 15:45 UTC by rossneilson

Just getting a couple of strange errors

`yarn hardhat --network localhost deploy-dxvote-develop`
`yarn hardhat --network localhost deploy-guilds-develop`

2022-05-05 12:49 UTC, AugustoL requested changes

2022-05-05 12:49 UTC, AugustoL commented on scripts/DeploymentTemplates/dxvote-develop.js
> +      guildActions: [
Running guildActions before or after the "dao" actions wont allow run actions in between them, and thats one of the things we want to tests in the DXDGuild.

I think we should be able to run dao and guild actions at the same time, this means having a single actions array, not actions a& guildActions

2022-05-05 12:49 UTC, AugustoL commented on scripts/utils/deploy-tokens.js
> +  // await Promise.all(
commended code and console log here

2022-05-05 12:49 UTC, AugustoL commented on scripts/utils/deploy-tokens.js
> +      case "ERC20":
lets use the ERC20 case on default.

2022-05-05 13:05 UTC, rossneilson commented on scripts/DeploymentTemplates/dxvote-develop.js
> +      guildActions: [
Good point, just means replicating some code but can do that

2022-05-05 13:06 UTC, rossneilson commented on scripts/utils/deploy-tokens.js
> +  // await Promise.all(
Was still debugging stuff but will remove it and comment once its all working

2022-05-17 20:37 UTC, MiltonTulli approved these changes

2022-05-17 20:42 UTC, AugustoL approved these changes

2022-05-17 20:42 UTC, merged