[WIP] Fix/create proposal with zero totallocked
DXgovernance/dxdao-contracts pull request #182
Opened 2022-06-17 15:28 UTC by MiltonTulli

Add minimum members validation before create proposal

2022-06-24 12:03 UTC, rossneilson submitted a review, later dismissed
Implementation looks good. I am still not convinced this really accomplishes much but if it satisfies the report and Augusto think its worthwhile then lets add it.

2022-06-28 16:12 UTC, AugustoL requested changes

2022-06-28 16:12 UTC, AugustoL commented on contracts/erc20guild/ERC20GuildUpgradeable.sol
> +        minimumMembersForProposalCreation = 0;
They are 0 by default alreayd, you can remove this.

2022-06-29 14:29 UTC, MiltonTulli commented on contracts/erc20guild/ERC20Guild.sol
> +        minimumMembersForProposalCreation = 0;
Done!

2022-06-29 14:29 UTC, MiltonTulli commented on contracts/erc20guild/ERC20GuildUpgradeable.sol
> +        minimumMembersForProposalCreation = 0;
Done!

2022-06-30 14:24 UTC, AugustoL approved these changes

2022-07-01 09:46 UTC, rossneilson approved these changes

2022-07-01 14:37 UTC, merged