Fix/gas refund on set vote
DXgovernance/dxdao-contracts pull request #185
Opened 2022-06-23 16:28 UTC by dcrescimbeni

Relates to issue #159, and DXD-11 in the audit.

Fixes `setVote` exploit when `voteGas` amount is set above the actual gas spent for the function call, enabling voters to get refunded more than what they spent to call the function.

It sets a hard limit of 100.000 gas (~85% of the actual 117.000 gas needed to execute `setVote()`).

2022-06-24 12:35 UTC, rossneilson commented
So we are going with the assumption that gas will be around that cost regardless of chain?

2022-06-24 13:35 UTC, dcrescimbeni commented
> So we are going with the assumption that gas will be around that cost regardless of chain?

That's the assumption, yes.

If that's not correct, then gas consumption must be calculated every time the function is called.

2022-06-28 09:17 UTC, rossneilson submitted a review, later dismissed

2022-06-28 16:05 UTC, AugustoL requested changes
Set the limit to 117 000, not 100 000

2022-06-28 18:13 UTC, dcrescimbeni commented
@AugustoL done!

2022-06-29 12:06 UTC, AugustoL requested changes

2022-06-30 00:00 UTC, dcrescimbeni commented on contracts/erc20guild/BaseERC20Guild.sol
> +        require(_voteGas <= 117000, "ERC20Guild: vote gas has to be equal or lower than 117.000");
Done!

2022-06-30 14:29 UTC, AugustoL approved these changes

2022-07-01 09:42 UTC, rossneilson approved these changes

2022-07-04 02:19 UTC, merged