[wip] Miscellaneous General Comments
DXgovernance/dxdao-contracts pull request #188
Opened 2022-06-27 15:49 UTC by MiltonTulli

Closes https://github.com/DXgovernance/dxdao-contracts/issues/175

2022-06-30 14:29 UTC, AugustoL approved these changes

2022-06-30 18:53 UTC, rossneilson submitted a review, later dismissed

2022-07-05 15:14 UTC, AugustoL requested changes
please squash commits

2022-07-06 12:03 UTC, rossneilson approved these changes

2022-07-06 19:06 UTC, AugustoL approved these changes

2022-07-06 19:08 UTC, merged