fix: change from transfer to call value
DXgovernance/dxdao-contracts pull request #189
Opened 2022-06-27 17:35 UTC by Kenny-Gin1

Change from `transfer` to `.call.value`

2022-06-28 10:09 UTC, rossneilson submitted a review, later dismissed

2022-06-28 15:56 UTC, AugustoL requested changes
Test missing, you can check by sending ETH to a contract that cannot doesnt have the fallback set.

2022-06-28 15:56 UTC, AugustoL commented on contracts/daostack/controller/Avatar.sol
> +        require(sent, "Failed to send ethers");
Change menssage to "eth transfer failed"

2022-06-28 16:41 UTC, Kenny-Gin1 commented
> Test missing, you can check by sending ETH to a contract that cannot doesnt have the fallback set.

You've written a test for this one already in `Controller.js` 

```var tx = await controller.sendEther(
      web3.utils.toWei("1", "ether"),
      otherAvatar.address,
      avatar.address
    );
    await avatar
      .getPastEvents("SendEther", {
        filter: { _addr: avatar.address }, // Using an array means OR: e.g. 20 or 23
        fromBlock: tx.blockNumber,
        toBlock: "latest",
      })
      .then(function (events) {
        assert.equal(events[0].event, "SendEther");
      });
    var avatarBalance =
      (await web3.eth.getBalance(avatar.address)) /
      web3.utils.toWei("1", "ether");
    assert.equal(avatarBalance, 0);
    var otherAvatarBalance =
      (await web3.eth.getBalance(otherAvatar.address)) /
      web3.utils.toWei("1", "ether");
    assert.equal(otherAvatarBalance, 1);
  });```

2022-06-30 14:28 UTC, AugustoL approved these changes

2022-06-30 23:20 UTC, merged