[wip] Feature/refactor dxavatar
DXgovernance/dxdao-contracts pull request #210
Opened 2022-08-17 14:03 UTC by MiltonTulli

Description:
Refactor the DXAvatar remove daostack code, updating the solidity compiler to v0.8.8.

Closes https://github.com/DXgovernance/dxdao-contracts/issues/202

2022-08-19 21:40 UTC, AugustoL requested changes

2022-08-19 21:40 UTC, AugustoL commented on contracts/dxdao/DxAvatar.sol
> +        (bool success, ) = _to.call{value: _value}(_data);
Lets also return the data form the function execution
```
(bool success, bytes dataReturened) = _to.call{value: _value}(_data);
```

And make the fuction return a (bool,bytes) to also return the dataReturn

2022-08-20 22:02 UTC, MiltonTulli commented on contracts/dxdao/DxAvatar.sol
> +        (bool success, ) = _to.call{value: _value}(_data);
Done!

2022-08-22 20:38 UTC, AugustoL approved these changes

2022-08-22 20:48 UTC, merged