Upgrade DXDVotingMachine solc version
DXgovernance/dxdao-contracts pull request #212
Opened 2022-08-18 16:22 UTC by dcrescimbeni

Closes #205 

1. Moved code from GenesisProtocol to DXDVotingMachine.
2. Reordered code.
3. Upgraded solidity from 0.5.11 to 0.8.8. Updated deprecated variables.
4. Moved `struct Proposal` mappings outside of the struct definition.

2022-08-19 21:35 UTC, AugustoL requested changes

2022-08-19 21:35 UTC, AugustoL commented on contracts/dxvote/DXDVotingMachine.sol
> +library RealMath {
Move this library to other contract in the contracts/utils folder

2022-08-20 15:02 UTC, dcrescimbeni commented on contracts/dxvote/DXDVotingMachine.sol
> +library RealMath {
Done!

2022-08-22 20:38 UTC, AugustoL approved these changes

2022-08-23 11:48 UTC, merged