DxController Refactor
DXgovernance/dxdao-contracts pull request #213
Opened 2022-08-20 06:15 UTC by mprasanjith

2022-08-22 20:37 UTC, AugustoL requested changes

2022-08-22 20:37 UTC, AugustoL commented on contracts/dxdao/DxController.sol
> +    DxAvatar public avatar;
Lets remove avatar, is not being used in the contract, it is required as parameter in some cases but with no need. Remove this, the onlyValidAvatar modifier and parameter in the register/unregister functions

2022-08-22 20:37 UTC, AugustoL commented on contracts/dxdao/DxController.sol
> +    function unregisterSelf(address _avatar) external onlyRegisteredScheme isAvatarValid(_avatar) returns (bool) {
Remove this function please, we will use unregisterScheme instead

2022-08-22 20:37 UTC, AugustoL commented on contracts/dxdao/DxController.sol
> +    address[] schemesAddresses;
This can be public

2022-08-22 20:37 UTC, AugustoL commented on contracts/dxdao/DxController.sol
> +    uint256 schemesWithManageSchemesPermission;
This can be public

2022-08-23 15:57 UTC, mprasanjith commented on contracts/dxdao/DxController.sol
> +    DxAvatar public avatar;
`avatar` is being used in the `avatarCall` function, so not sure if I should still remove this.

2022-08-25 16:37 UTC, AugustoL requested changes
Remove the changes done in DaoCreator please :grimacing:

2022-08-26 13:08 UTC, AugustoL approved these changes

2022-08-26 13:08 UTC, merged