fix A2-A4 recommendations by omega
DXgovernance/dxdao-contracts pull request #245
Opened 2022-10-25 17:06 UTC by Kenny-Gin1

Closes: 
#242 #243 #244 

**Description**
This PR refers to the findings of Omega, namely A2 - A4. Concretely it fixes the following: 

- Setting the `ProposalState.ExecutionSucceeded` outside of the loop to avoid multiple updates to the proposal state.
- Following the `[checks-effects-interactions`-pattern](https://docs.soliditylang.org/en/develop/security-considerations.html#use-the-checks-effects-interactions-pattern) and moving the proposal state changes before the external calls.
- Removing the `require` criterion that checks if the scheme is approved to make avatar calls since this require is redunadnt.

2022-10-27 00:16 UTC, rulfo71 commented on contracts/dao/schemes/AvatarScheme.sol
> + * generic calls to the dao controller. If the controller address is not set it will e executing raw calls from the
```suggestion
 * generic calls to the dao controller. If the controller address is not set it will be executing raw calls from the

```

2022-10-27 12:28 UTC, dcrescimbeni approved these changes

2022-10-31 14:02 UTC, AugustoL requested changes

2022-10-31 14:49 UTC, Kenny-Gin1 commented on contracts/dao/schemes/AvatarScheme.sol
> +
This is now addressed!

2022-11-02 14:34 UTC, AugustoL approved these changes

2022-11-03 10:51 UTC, merged