R1 - snapshot is called unnecessarily too often
DXgovernance/dxdao-contracts pull request #247
Opened 2022-10-27 17:32 UTC by rulfo71

Closes: #239 

**Description**
The problem on this item was that we were taking a snapshot each time we minted or burned REP. This is unnecesary because the only moment we need the snapshot is when we are creating a proposal. 
The solution i did was only taking a snapshot when creating a proposal (on DAOController.sol). 
This has a (negative?) consequence, that the snapshot is not updated all the time, so if someone calls getCurrentSnapshotId() may not get the correct snapshot. 

At the moment this is not a problem because every time this function is called is when a proposal is being created, but maybe it could be a problem in the future. 

I talked to @dcrescimbeni and we agreed to do this, and ask here for your comments so let me know  what you think.

2022-10-31 12:24 UTC, AugustoL requested changes

2022-10-31 12:24 UTC, AugustoL commented on contracts/dao/DAOReputation.sol
> -            _snapshot();
The issue here was that the snapshot was being taken a right after _burn and _mint functions in the multiple functions, executing the snapshot unnecessarily cause it was already executed in the internal functions.

We want to take a snapshot every time a burn and mint occurs, not only when a proposal is created, when a proposal is created we get the snapshot id.

2022-11-01 11:40 UTC, dcrescimbeni approved these changes

2022-11-01 13:41 UTC, rulfo71 commented on contracts/dao/DAOReputation.sol
> -            _snapshot();
done

2022-11-02 14:34 UTC, AugustoL approved these changes

2022-11-02 18:11 UTC, merged