refactor: allow gas refunds for contracts
DXgovernance/dxdao-contracts pull request #291
Opened 2023-01-04 13:24 UTC by fnanni-0

Gas refunds are only allowed when using an EOA to vote. This is enforced using an [isContract() check](https://github.com/DXgovernance/dxdao-contracts/blob/54410e27dc25bb580d5fb99b60509b0d38889098/contracts/erc20guild/BaseERC20Guild.sol#L481) before refunding. However, isContract() returns false if msg.sender is a contract in construction.

If isContract() was a counter-measure against reentrancy, it achieves nothing, although I don't see how reentrancy could do any harm in this case. If this is the case, I suggest removing it.

If isContract() was meant to cap refunds when batching signature votes or similar, I'm not sure what is the need for that, but it could be fooled using a contract in construction.

2023-01-16 14:58 UTC, AugustoL requested changes
tests missing

2023-01-18 14:27 UTC, fnanni-0 commented
I've been thinking more about this and I have a concern about gas refunds.

Updating a vote costs ~66k gas. If voteGas is set somewhere between 66k-117k, this means that voting could be profitable by iteratively calling `setVote(proposalId, option, previous vote voting power + 1)` until the guild balance is drain. Even if voteGas is set below 66k gas, someone could grief and drain a guild while bearing a small cost. Batching setVotes from a smart contract (either during construction if isContract() is used or using a tx batcher contract) makes this worse.

Are gas refunds and this gas refund technic in particular used in other DAOs?

2023-01-23 18:24 UTC, AugustoL requested changes

2023-01-24 19:10 UTC, AugustoL approved these changes

2023-02-02 15:35 UTC, merged