fix: execute erc20 limit removal after delay
DXgovernance/dxdao-contracts pull request #292
Opened 2023-01-04 13:45 UTC by fnanni-0

[removeERC20Limit()](https://github.com/DXgovernance/dxdao-contracts/blob/0867dbaf13b26d92bd2af73059ed230887e58dcb/contracts/utils/PermissionRegistry.sol#L148-L155) sets a delay to the actual removal of the limit, which will be executed by calling `executeRemoveERC20Limit()`. However, currently  the [execution is allowed](https://github.com/DXgovernance/dxdao-contracts/blob/0867dbaf13b26d92bd2af73059ed230887e58dcb/contracts/utils/PermissionRegistry.sol#L164) UNTIL the delay has passed instead of ONCE the delay has passed.

2023-01-17 05:40 UTC, fnanni-0 commented
There was another issue that was fixed:
Removed erc20 limits remain on the `erc20Limits` array as empty elements. This means that `endProposal()` would always revert after a limit removal, because `setERC20Balances()` and `checkERC20Limits()` would call `balanceOf()` on a 0x0 token contract address.

Also, with the original fix `executeRemoveERC20Limit()` wouldn't revert if called on a limit with `removeTime` equal 0. That was fixed as well.

2023-01-17 13:33 UTC, AugustoL requested changes

2023-01-17 13:33 UTC, AugustoL commented on test/erc20guild/ERC20Guild.js
> +    });
Lets execute the removal here, check that it was removed and try to execute the same proposal and fail.

2023-01-17 13:33 UTC, AugustoL commented on test/erc20guild/ERC20Guild.js
> +                .executeRemoveERC20Limit(erc20Guild.address, 0)
lets tests also executing the removal from an EOA

2023-01-17 17:47 UTC, fnanni-0 commented
@AugustoL in order to modify an existing ERC20 limit, the guild would need to remove it, wait, execute the removal and then add the new ERC20 limit. Is this the intended behavior? In this scenario there would be a time window during which there is no transfer limit to the ERC20 that the guild is trying to update.

2023-01-17 18:04 UTC, fnanni-0 commented on test/erc20guild/ERC20Guild.js
> +    });
The same proposal shouldn't fail after the removal execution, should it?

2023-01-20 15:05 UTC, fnanni-0 commented
New fixes:
- initialValue was incorrectly set when addERC20Limit() was called by owner()
- It was possible to duplicate ERC20 token limits after removal
- Now it’s possible to update an ERC20 limit after delay without removing the limit first

Working on tests now.

2023-01-23 18:20 UTC, AugustoL requested changes

2023-01-23 18:20 UTC, AugustoL commented on contracts/utils/PermissionRegistry.sol
>       * @dev Removes an ERC20 limit of an address by its index in the ERC20Lmits array.
Update instead of remove

2023-01-24 18:56 UTC, AugustoL approved these changes

2023-01-24 19:02 UTC, merged