Feat/fast proposal execution
DXgovernance/dxdao-contracts pull request #310
Opened 2023-02-10 23:11 UTC by fnanni-0

A new configurable variable is added: `minVotePercentageForExecution`. If set, proposals that get an amount of votes for an option greater than `minVotePercentageForExecution` can be executed immediately without waiting till the `proposalTime` has passed.

`minVotePercentageForExecution` is expressed in basis points as a proportion of the total supply of the guild's token. If set, values must be between 5000 (50%) and 10000 (100%). For example, if set to 7500, a proposal must have at least 75% of the token's total supply supporting the winning option in order to end early.

2023-02-28 13:21 UTC, AugustoL reviewed
I think it would be better use the name votingPowerPercentageForInstantProposalExecution instead of minVotePercentageForExecution

2023-02-28 13:24 UTC, AugustoL commented
Later we might should do a PR changing all the variable names to shorter ones

2023-03-02 03:32 UTC, fnanni-0 commented on contracts/erc20guild/BaseERC20Guild.sol
>                      try
@AugustoL can the try/catch be removed? It doesn't seem to be doing anything.

2023-03-06 14:38 UTC, MiltonTulli commented on test/erc20guild/implementations/SnapshotERC20Guild.js
> +      //
You can remove this

2023-03-06 14:39 UTC, MiltonTulli commented on test/erc20guild/implementations/SnapshotERC20Guild.js
> +      // await time.increase(time.duration.seconds(61));
Remove this line

2023-03-06 14:39 UTC, MiltonTulli commented on test/erc20guild/implementations/SnapshotERC20Guild.js
> +      // await time.increase(time.duration.seconds(61));
You can remove this

2023-03-06 17:54 UTC, fnanni-0 commented on contracts/erc20guild/BaseERC20Guild.sol
> +    uint256 internal constant BASIS_POINT_MULTIPLIER = 10_000;
I think not. I left `MAX_OPTIONS_PER_PROPOSAL` public because it's a relevant variable for the user to see (although you can always check it if the contract is verified) and in case future guilds use a different constant, but `internal` seems appropriate for `BASIS_POINT_MULTIPLIER`.

2023-03-06 18:13 UTC, AugustoL requested changes

2023-03-06 18:13 UTC, AugustoL commented on contracts/erc20guild/BaseERC20Guild.sol
> +
Missing description of functions

2023-03-06 18:13 UTC, AugustoL commented on contracts/erc20guild/BaseERC20Guild.sol
>                      try
Si

2023-03-08 12:49 UTC, AugustoL approved these changes

2023-03-09 14:30 UTC, merged