Contracts/guild factory
DXgovernance/dxdao-contracts pull request #92
Opened 2022-03-15 18:29 UTC by Kenny-Gin1

- Created a smart contract called `GuildRegistry` that should handle adding and removing guilds and some additional helper methods.
- Added tests (checked for 100% coverage
<img width="655" alt="Screenshot 2022-03-15 at 18 41 35" src="https://user-images.githubusercontent.com/59825171/158446911-37852d29-c155-4441-bf3f-d724e67ce14e.png">

2022-03-16 08:28 UTC, carlbarrdahl commented on contracts/erc20guild/utils/GuildRegistry.sol
> +        guildStructs[guildAddressToMove].index = guildIndexToDelete;
Should the mapping `guildStructs[guildAddress]` be deleted here to free up storage?

2022-03-16 09:39 UTC, Kenny-Gin1 commented on contracts/erc20guild/utils/GuildRegistry.sol
> +        guildStructs[guildAddressToMove].index = guildIndexToDelete;
Hmm, I am afraid I don't understand your suggestion. Could you write out your proposal? :)

2022-03-16 09:45 UTC, carlbarrdahl commented on contracts/erc20guild/utils/GuildRegistry.sol
> +        guildStructs[guildAddressToMove].index = guildIndexToDelete;
I'm still learning solidity so this is more a question to understand it better :)

The code keeps track of guilds with the mapping `guildStructs` and an array of addresses (`_guilds`). When a guild is removed the array is cleaned up with `_guilds.pop` but the struct is still there. Could this be a problem as the number of guilds are created? Is it possible (or useful) to:
`delete guildStructs[guildAddress]`

2022-03-16 09:47 UTC, rossneilson commented on contracts/erc20guild/utils/GuildRegistry.sol
> +        guildStructs[guildAddressToMove].index = guildIndexToDelete;
We could maybe consider just having it be a simple address  => uint256 mapping if we don't end up adding more attributes here which Im not certain we will

2022-03-16 11:26 UTC, AugustoL requested changes
I requested some changes, but the code looks good, great job :)

After this PR it would be good to add other test where a guild is added and remove with dxvote proposals :)

2022-03-16 11:26 UTC, AugustoL commented on contracts/erc20guild/utils/GuildRegistry.sol
> +    Counters.Counter private _index;
no need to use private variables, there is no private information here and no need to protect this variables, use public instead.

2022-03-16 11:26 UTC, AugustoL commented on contracts/erc20guild/utils/GuildRegistry.sol
> +        guildStructs[guildAddressToMove].index = guildIndexToDelete;
What @carlbarrdahl is suggesting is to also remove the guild in the guildsStruct that is indexing it by index, you can free up some storage of the contract and it will be a bit cheaper to add information later, you are removing it in the array but not in the index.

2022-03-16 11:26 UTC, AugustoL commented on contracts/erc20guild/utils/GuildRegistry.sol
> +    mapping(address => Guild) guildStructs;
The Guild is a struct, but this is an index, I would recommend naming it `guildsByAddress`, so when you read teh variable name you know that you can access the guild information in the mapping by just the address.

2022-03-16 11:26 UTC, AugustoL commented on contracts/erc20guild/utils/GuildRegistry.sol
> +
Can you add natspect comments? the ERC20Guild has them, yo can also take a look here https://docs.soliditylang.org/en/v0.5.8/natspec-format.html

2022-03-16 11:26 UTC, AugustoL commented on test/erc20guild/utils/GuildRegistry.js
> +    return {
unnecessary return here ?

2022-03-16 13:19 UTC, Kenny-Gin1 commented
> I requested some changes, but the code looks good, great job :)
> 
> After this PR it would be good to add other test where a guild is added and remove with dxvote proposals :)

Thank you Augusto, appreciate it 👍. I will look at the comments and see if I can make the changes!

2022-03-19 12:19 UTC, Kenny-Gin1 commented
The latest commit includes:

- Removed the `Guild struct` since we are not sure if we want to add more attributes to the `GuildRegistry`. @rossneilson 
- Changed variable names and made certain variables public
- Added natspec comment as per @AugustoL suggestion above

2022-03-21 11:48 UTC, AugustoL approved these changes

2022-03-21 11:51 UTC, merged